### ISSUE TITLE
Jeremy Hughes Feedback

### ISSUE THREAD

**Issue by longshorej** [lightbend/lightbend-orchestration-docs#15]
I haven't really had time to grok what Jeremy is asking for, but tracking it here:

> Jeremy Hughes [10:34 AM] 
@longshorej-guest perhaps it’s just me, but I would have expected the last line of the sbt output to indicate the total time taken, rather than just the time of the last of the 3 jobs
>
> Jeremy Hughes [10:48 AM] 
Another feedback item on the hello-reactive-tooling example… there’s this:
>
> https://files.slack.com/files-tmb/T27SFGS2W-F8WGAFD4K-fb8e73ecef/image_720.png
>
> Jeremy Hughes [10:48 AM] 
and some verbose output from curl giving TLS handshake info etc … would be good to point out a few important lines from that output
>
> [10:49] 
> maybe in this case just:
> ```Host: 192.168.99.102```

**Comment by dwijnand** [comment]
Let's open these as distinct issues.. if they come up again.
