### ISSUE TITLE
Document Kubernetes RBAC configuration

### ISSUE THREAD

**Issue by longshorej** [lightbend/lightbend-orchestration-docs#30]
For RBAC-enabled clusters, we should document what permissions are required.

See also: 
https://github.com/akka/akka-management/issues/137
https://github.com/akka/akka-management/pull/138/files

**Comment by petervandenabeele** [comment]
FWIW, this is a variant of this command that is a bit easier (taken from Weaveworks Flux documentation):
```
kubectl create clusterrolebinding "cluster-admin-$(whoami)" --clusterrole=cluster-admin --user="$(gcloud config get-value core/account)"
```
