### ISSUE TITLE
Travis (or other) CI

### ISSUE THREAD

**Issue by longshorej** [lightbend/lightbend-orchestration-docs#33]
Seems this project doesn't have CI enabled. It would have to be made public to use Travis, but I think that would be okay and might encourage some community-sourced fixes.

**Comment by dwijnand** [comment]
The repo is public now. What kind of integration is of interest here?

**Comment by TimMoore** [comment]
We could start with something minimal, such as ensuring that `sbt paradox` runs successfully.

Maybe in the future we could consider automating deployment.
