### ISSUE TITLE
Support installation on Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by patrick-premont** [lightbend/lightbend-orchestration-docs#38]
The install instructions for reactive-cli on Ubuntu fails (version 18 used), during the `apt-get update` part, with:

```
Hit:1 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                            
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                          
Ign:4 https://dl.bintray.com/lightbend/deb bionic InRelease                                                                                                                           
Err:5 https://dl.bintray.com/lightbend/deb bionic Release                                      
  404  Not Found [IP: 75.126.118.188 443]
Hit:6 http://archive.canonical.com/ubuntu bionic InRelease               
Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease        
Reading package lists... Done                      
E: The repository 'https://dl.bintray.com/lightbend/deb bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

On Debian (version 9 used), the situation is not quite as bad, but probably still needs attention:

If you first do this, as #37 recommends, to avoid an installation error,
```
    sudo apt-get install apt-transport-https
```
and then install, you get this security warning:
```
The following NEW packages will be installed:
  libre2-3 libunwind8 reactive-cli
0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,468 kB of archives.
After this operation, 725 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  reactive-cli
Install these packages without verification? [y/N] 
```

Perhaps those two issues are related, even though they appear to cause problems at different steps?

**Comment by mitkus** [comment]
Thanks, I triggered bintray metadata recalculation.

Change with Ubuntu 18.04 support landed in reactive-cli master branch, an official release will come out this week.

**Comment by carwilki** [comment]
Any updates on this? Still getting the above error on bionic.

**Comment by TimMoore** [comment]
@mitkus can you update? I see that shortly after the support for Bionic was added, it was disabled in https://github.com/lightbend/reactive-cli/commit/9b4e47cbf33b7f6699fe34760cc39c21592ca6d9. Could you explain what the problem was?

**Comment by TimMoore** [comment]
This looks the same as https://github.com/lightbend/reactive-cli/issues/144. I'll close this in favor of that one, since it is an issue with the `reactive-cli` release process and not the documentation.

**Comment by TimMoore** [comment]
This has been resolved. There's a release of reactive-cli 1.3.0 for Ubuntu 18.04 available in our deb repository.
