### ISSUE TITLE
Improve Akka Cluster Bootstrap documentation

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/lightbend-orchestration-docs#55]
Some comments from @ktoso in https://github.com/lightbend/lightbend-orchestration-docs/pull/54

```diff
+ When you generate resources for a deployment, you'll need to specify a replica count greater than 2. A value of 3 or
+ 5 is recommended. This is to reduce the risk of multiple islands of clusters being formed when first formed. For example,
+ the following command specifies 5 replicas which are used as the contact points for forming the cluster:
```

> The wording is a bit confusing here. Is this conflating the minimum number of nodes bootstrap expects with the number of how many replicas we start? Is it automagically set to the same number?

**Comment by TimMoore** [comment]
I didn't realize this until I just went searching while writing this comment, but it looks like the `rp` CLI _does_ automatically set these to the same number: https://github.com/lightbend/reactive-cli/blob/7993357be8b908af1a9016e7fd90f797b73ea16f/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/marathon/RpEnvironmentVariables.scala#L62

**Comment by dwijnand** [comment]
What's the documentation improvement we'd like to see here? As someone not well-versed with akka management cluster bootstrap it's unclear to me.

**Comment by eed3si9n** [comment]
Replica is a Kubernetes term for the number of copies it launches for a specific service deployment (e.g. `hello-impl`). Akka Cluster uses the term _node_ to describe the worker program. Akka Cluster Bootstrap helps helps an Akka Cluster to form in Kubernetes without hardcoding the seed node IP addresses, which is not natural for k8s.
 
I think there are several layers to this issue:
1. Is the current Lightbend Orchestration (for example the config that Tim found) behavior sound?
2. Is the current documentation recommendation sound? (Pick an odd number greater than 2, like 3 or 5)
3. What should we add/remove to clarify the writing?

### required-contact-point-nr

Suppose that the number of Akka Cluster node fluctuates between 10 to 100 depending on the load, and initially we launch 10. Akka Management's documentation seems to suggest that `required-contact-point-nr` should be set to " the exact number of nodes the initial startup of the cluster will be done."

### odd number greater than 2

It sounds plausible, yet it doesn't make sense. Assuming that network is never reliable, and that the Akka clusters are scaling up and down, the whole idea that total node must be divisible by 2 I am not sure would add up. Akka Cluster uses failure detector to monitor each other's heart beat, and having odd number I am not sure would help.

> This is to reduce the risk of multiple islands of clusters being formed when first formed.

If we are setting `required-contact-point-nr` to 10, then why would we get islands? The odd/even hints towards the idea of Split Brain Resolver's keep-majority, but keep-majority is actually smart enough to break the tie using the lowest IP address iirc.

@ktoso Could you confirm/deny these points plz?

**Comment by TimMoore** [comment]
This has been improved in the Akka Management documentation.

https://developer.lightbend.com/docs/akka-management/current/bootstrap/index.html#initial-deployment

Further improvements should target those docs.
