### ISSUE TITLE
Follow up on Additional Application and Jobs documentation

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/lightbend-orchestration-docs#57]
https://github.com/lightbend/lightbend-orchestration-docs/pull/54#discussion_r207445949

This mechanism might change later.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
