### ISSUE TITLE
Define "Incubating" (or point to an external definition)

### ISSUE THREAD

**Issue by TimMoore** [lightbend/lightbend-orchestration-docs#61]
With the recent documentation update, several page refer to integration with Kubernetes or DC/OS as "Incubating" but don't define what this means.

**Comment by TimMoore** [comment]
I'll work with the other product managers to determine where we want to publish these definitions.

**Comment by ktoso** [comment]
@ennru likely to be in the loop here since alpakka coining those terms too

**Comment by TimMoore** [comment]
Moving this back into the backlog because we are still working on consistent definitions to apply across all Lightbend products.

**Comment by TimMoore** [comment]
These definitions have been published to https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html

The Lightbend Orchestration documentation site has been updated with the current status, linking to the definitions on that page:

Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
