### ISSUE TITLE
Akka tutorial with minikube

### ISSUE THREAD

**Issue by chbatey** [lightbend/lightbend-orchestration-docs#62]
Something like https://developer.lightbend.com/docs/enterprisesuiteconsole/beta/tutorial/index.html but for just an Akka HTTP / Cluster application.

I used the plugin/CLI for the first time and as I was using Kubernetes I ended up here (https://developer.lightbend.com/docs/lightbend-orchestration/current/kubernetes-development.html) but it uses a Lagom application where most things happen magically. I had an Akka app with multiple mains and using Akka gRPC and was quite lost on how to do it.

Perhaps it is about making this more visible / including a section in the docs for "Working with Akka"

**Comment by chbatey** [comment]
Happy to help contribute this if we plan to recommend this for pure Akka applications.

**Comment by eed3si9n** [comment]
I similar frustrating experience trying to use it with Play, so I wrote https://developer.lightbend.com/docs/lightbend-orchestration/current/getting-started/sbt-play-minikube.html

**Comment by TimMoore** [comment]
Can we close this now that we have https://developer.lightbend.com/docs/akka-management/current/bootstrap/recipes.html?
