### ISSUE TITLE
Documentation is not explicit about Lagom's describeService

### ISSUE THREAD

**Issue by renatocaval** [lightbend/lightbend-orchestration-docs#66]
We should add to the documentation that we recommend the usage of Lagom's `describeService`.  

In this [part of the docs](https://developer.lightbend.com/docs/lightbend-orchestration/current/setup/project-configuration.html#sbt-settings-tasks) we say that it defaults to service name in Lagom, but that's only true if using `describeService`.

We could add this information to the section about [Service Location](https://developer.lightbend.com/docs/lightbend-orchestration/current/features/service-location.html) in the `LagomLoader` example.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
