### ISSUE TITLE
Better explain `rp` options

### ISSUE THREAD

**Issue by longshorej** [lightbend/lightbend-orchestration-docs#7]
In the examples, `rp` invocation is shown but focuses on brevity instead of clarity. We should better explain what the options are, why they're needed, etc.

We should also consider a workflow where users store the output in git, a common practice. Still giving this some thought.

/cc @longmuir

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
