### ISSUE TITLE
Refer to the new Lightbend helm-charts repo

### ISSUE THREAD

**Issue by marcoderama** [lightbend/lightbend-orchestration-docs#70]
The default location for the Lightbend helm-charts repo has moved to https://repo.lightbend.com/helm-charts and the old location (https://lightbend.github.io/helm-charts) is deprecated (and may go away at some point). References in the doco should use the new location.

**Comment by marcoderama** [comment]
Suggested fix in PR https://github.com/lightbend/lightbend-orchestration-docs/pull/69

**Comment by TimMoore** [comment]
This was fixed in #69
