### ISSUE TITLE
Document a version matrix.

### ISSUE THREAD

**Issue by ignasi35** [lightbend/lightbend-orchestration-docs#73]
See https://github.com/lagom/lagom/issues/1708#issuecomment-453214696 for details.

**Comment by ignasi35** [comment]
Thanks @TimMoore !

for reference: https://github.com/lightbend/lightbend-orchestration-docs/issues/73

**Comment by ignasi35** [comment]
After [comments](https://github.com/lagom/lagom/issues/1708#issuecomment-453567485) from @TimMoore, @eed3si9n  and myself, I think this is no longer necessary.

**Comment by eed3si9n** [comment]
I'll close this for now.
